apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hemanthkuncha06@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.mysite06.duckdns.org
          solverName: duckdns
          config:
            # Changed from tokenSecretRef to apiTokenSecretRef
            apiTokenSecretRef:
              name: duckdns-token-secret
              key: token
