apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
<<<<<<< HEAD
        image: hemanthuser/three-tier-frontend-ssl:4
=======
        image: hemanthuser/three-tier-frontend:2
>>>>>>> 78333d667b30019e58a9b0ae2f1efe897c353931
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "https://myapp.local/api/tasks"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    #nodePort: 30101
  #type: NodePort
  type: ClusterIP
  selector:
    role: frontend